[manager]
ratio = [0, 15, 85]
sort_dir_first = true
sort_by = "alphabetical"
show_hidden = true
show_symlink = true

[preview]
wrap = "yes"

[confirm]
delete = false
trash = false
overwrite = false
quit = false
