inherits = 'base16_transparent'

# "ui.background" = { fg = "#ffffff", bg = "#000000" }
# "ui.background.separator" = { fg = "#ffffff", bg = "#000000" }
# "ui.cursor" = { fg = "#ffffff", bg = "#000000" }
# "ui.cursor.normal" = { fg = "#ffffff", bg = "#000000" }
# "ui.cursor.insert" = { fg = "#ffffff", bg = "#000000" }
# "ui.cursor.select" = { fg = "#ffffff", bg = "#000000" }
# "ui.cursor.match" = { fg = "#ffffff", bg = "#000000" }
# "ui.cursor.primary" = { fg = "#ffffff", bg = "#000000" }
# "ui.cursor.primary.normal" = { fg = "#ffffff", bg = "#000000" }
# "ui.cursor.primary.insert" = { fg = "#ffffff", bg = "#000000" }
# "ui.cursor.primary.select" = { fg = "#ffffff", bg = "#000000" }
# "ui.debug.breakpoint" = { fg = "#ffffff", bg = "#000000" }
# "ui.debug.active" = { fg = "#ffffff", bg = "#000000" }
# "ui.gutter" = { fg = "#ffffff", bg = "#000000" }
# "ui.gutter.selected" = { fg = "#ffffff", bg = "#000000" }
# "ui.highlight.frameline" = { fg = "#ffffff", bg = "#000000" }
# "ui.linenr" = { fg = "#ffffff", bg = "#000000" }
# "ui.linenr.selected" = { fg = "#ffffff", bg = "#000000" }
# "ui.statusline" = { fg = "#ffffff", bg = "#80000080" }
# "ui.statusline.inactive" = { fg = "#ffffff", bg = "#000000" }
# "ui.statusline.normal" = { fg = "#ffffff", bg = "#000000" }
# "ui.statusline.insert" = { fg = "#ffffff", bg = "#000000" }
# "ui.statusline.select" = { fg = "#ffffff", bg = "#000000" }
# "ui.statusline.separator" = { fg = "#ffffff", bg = "#000000" }
# "ui.bufferline" = { fg = "#ffffff", bg = "hsl(0, 0%, 75%)" }
"ui.bufferline.active" = "slow_blink"
# "ui.bufferline.background" = { fg = "#ffffff", bg = "#000000" }
# "ui.popup" = { fg = "#ffffff", bg = "#000000" }
# "ui.popup.info" = { fg = "#ffffff", bg = "#000000" }
# "ui.window" = { fg = "#ffffff", bg = "#000000" }
# "ui.help" = { fg = "#ffffff", bg = "#000000" }
# "ui.text" = { fg = "#ffffff", bg = "#000000" }
# "ui.text.focus" = { fg = "#ffffff", bg = "#000000" }
# "ui.text.inactive" = { fg = "#ffffff", bg = "#000000" }
# "ui.text.info" = { fg = "#ffffff", bg = "#000000" }
# "ui.virtual.ruler" = { fg = "#ffffff", bg = "#000000" }
# "ui.virtual.whitespace" = "#4f4f4f"
# "ui.virtual.whitespace" = { fg = "#ffffff", bg = "#000000" }
# "ui.virtual.indent-guide" = { fg = "#ffffff", bg = "#000000" }
# "ui.virtual.inlay-hint" = { fg = "#ffffff", bg = "#000000" }
# "ui.virtual.inlay-hint.parameter" = { fg = "#ffffff", bg = "#000000" }
# "ui.virtual.inlay-hint.type" = { fg = "#ffffff", bg = "#000000" }
# "ui.virtual.wrap" = { fg = "#ffffff", bg = "#000000" }
# "ui.virtual.jump-label" = { fg = "#ffffff", bg = "#000000" }
# "ui.menu" = { fg = "#ffffff", bg = "#000000" }
# "ui.menu.selected" = { fg = "#ffffff", bg = "#000000" }
# "ui.menu.scroll" = { fg = "#ffffff", bg = "#000000" }
"ui.selection" = { fg = "#000000", bg = "#ffffff" }
"ui.selection.primary" = { fg = "#000000", bg = "#ffffff" }
"ui.highlight" = { fg = "#ffffff", bg = "#000000" }
# "ui.cursorline.primary" = { fg = "#ffffff", bg = "#000000" }
# "ui.cursorline.secondary" = { fg = "#ffffff", bg = "#000000" }
# "ui.cursorcolumn.primary" = { fg = "#ffffff", bg = "#000000" }
# "ui.cursorcolumn.secondary" = { fg = "#ffffff", bg = "#000000" }
# "warning" = { fg = "#ffffff", bg = "#000000" }
# "error" = { fg = "#000000", bg = "#000000" }
# "error" = { fg = "#ffffff" }
# "info" = { fg = "#ffffff", bg = "#000000" }
# "hint" = { fg = "#ffffff", bg = "#000000" }
# "diagnostic" = { bg = "#777777" }
# "diagnostic.hint" = { fg = "#ffffff", bg = "#000000" }
# "diagnostic.info" = { fg = "#ffffff", bg = "#000000" }
# "diagnostic.warning" = { fg = "#ffffff", bg = "#000000" }
# "diagnostic.error" = { fg = "#ffffff", bg = "#000000" }
# "diagnostic.error" = { fg = "#ffffff", bg = "#000000" }
# "diagnostic.error" = { fg = "#000000" }
# "diagnostic.unnecessary" = { fg = "#ffffff", bg = "#000000" }
# "diagnostic.deprecated" = { fg = "#ffffff", bg = "#000000" }

