[startup]
items = [
"ghostty -e helix ~/lince-social/dev",
"waybar",
"swww-daemon",
'swww img -t grow --transition-duration 0.7 "$(find ~/xaviduds/dotfiles/wallpapers/programar -type f | shuf -n 1)" > /dev/null',
"firefox"
]


/home/eduardo/Downloads
/home/eduardo/creatus
/home/eduardo/.ignore
/home/eduardo/.rustup
/home/eduardo/.mozilla
/home/eduardo/lince-social
/home/eduardo/.local
/home/eduardo/.gitconfig
/home/eduardo/.ssh
/home/eduardo/.config
/home/eduardo/.cargo
/home/eduardo/xaviduds
/home/eduardo/.cache/ola
/home/eduardo/.config/helix
/home/eduardo/.config/ghostty
/home/eduardo/.config/Postman
/home/eduardo/.config/anicca
/home/eduardo/.config/helix
/home/eduardo/.config/hypr
/home/eduardo/.config/lince
/home/eduardo/.config/nushell
/home/eduardo/.config/starship.toml
/home/eduardo/.config/waybar
/home/eduardo/.config/yazi
/home/eduardo/.config/carapace
