alias e="exit"
alias n="nvim"
alias z="clear && ls -1A --group-directories-first"
alias ns="nix-shell"
alias nl="nix-shell ~/lince-social/lince"

shopt -s autocd
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

