[nicca]
list = [
  "/home/eduardo/Downloads",
  "/home/eduardo/creatus",
  "/home/eduardo/.ignore",
  "/home/eduardo/.rustup",
  "/home/eduardo/.mozilla",
  "/home/eduardo/lince-social",
  "/home/eduardo/.local",
  "/home/eduardo/.gitconfig",
  "/home/eduardo/.ssh",
  "/home/eduardo/.config",
  "/home/eduardo/.cargo",
  "/home/eduardo/xaviduds",
  "/home/eduardo/.config/helix",
  "/home/eduardo/.config/ghostty",
  "/home/eduardo/.config/Postman",
  "/home/eduardo/.config/anicca",
  "/home/eduardo/.config/helix",
  "/home/eduardo/.config/hypr",
  "/home/eduardo/.config/lince",
  "/home/eduardo/.config/nushell",
  "/home/eduardo/.config/starship.toml",
  "/home/eduardo/.config/waybar",
  "/home/eduardo/.config/yazi",
  "/home/eduardo/.config/carapace",
]

[dotfiles]
method = "remove and copy over"
"/home/eduardo/.gitconfig" = "/home/eduardo/dotfiles/git/.gitconfig"
"/home/eduardo/.ignore" = "/home/eduardo/dotfiles/helix/.ignore"
"/home/eduardo/.config/helix" = "/home/eduardo/dotfiles/helix"
"/home/eduardo/.config/ghostty" = "/home/eduardo/dotfiles/ghostty"
"/home/eduardo/.config/nushell/config.nu" = "/home/eduardo/dotfiles/nushell/config.nu"
"/home/eduardo/.config/nushell/env.nu" = "/home/eduardo/dotfiles/nushell/env.nu"
"/home/eduardo/.config/hypr" = "/home/eduardo/dotfiles/hypr"
"/home/eduardo/.config/waybar" = "/home/eduardo/dotfiles/waybar"
"/home/eduardo/.config/lince/os.toml" = "/home/eduardo/dotfiles/lince/os.toml"
"/home/eduardo/.config/starship.toml" = "/home/eduardo/dotfiles/starship.toml"
"/home/eduardo/.config/yazi" = "/home/eduardo/dotfiles/yazi"
