alias ns="nix-shell"
alias nl="nix-shell ~/lince-social/lince"
alias pl="python ~/lince-social/lince/src/terminal.py"
alias fl="python ~/lince-social/lince/src/flask_app.py"
alias z="clear && ls -1A --group-directories-first"
alias co="cd /home/eduardo/.config && z"
alias dt="cd /home/eduardo/xaviduds/dotfiles && z"
alias l="cd /home/eduardo/lince-social/lince && z"
alias n="nvim"
alias d="cd Downloads && z"
alias e="exit"
shopt -s autocd

# [ "$PWD" != "$HOME" ] && [ -z "$NU_ENV" ] && exec nu
